/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiSolutionsRouteImport } from './routes/ai-solutions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsSanLuisObispoRouteImport } from './routes/locations.san-luis-obispo'
import { Route as LocationsPasoRoblesRouteImport } from './routes/locations.paso-robles'
import { Route as LocationsAtascaderoRouteImport } from './routes/locations.atascadero'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSolutionsRoute = AiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSanLuisObispoRoute = LocationsSanLuisObispoRouteImport.update({
  id: '/locations/san-luis-obispo',
  path: '/locations/san-luis-obispo',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsPasoRoblesRoute = LocationsPasoRoblesRouteImport.update({
  id: '/locations/paso-robles',
  path: '/locations/paso-robles',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsAtascaderoRoute = LocationsAtascaderoRouteImport.update({
  id: '/locations/atascadero',
  path: '/locations/atascadero',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/atascadero': typeof LocationsAtascaderoRoute
  '/locations/paso-robles': typeof LocationsPasoRoblesRoute
  '/locations/san-luis-obispo': typeof LocationsSanLuisObispoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/atascadero': typeof LocationsAtascaderoRoute
  '/locations/paso-robles': typeof LocationsPasoRoblesRoute
  '/locations/san-luis-obispo': typeof LocationsSanLuisObispoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-solutions': typeof AiSolutionsRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/locations/atascadero': typeof LocationsAtascaderoRoute
  '/locations/paso-robles': typeof LocationsPasoRoblesRoute
  '/locations/san-luis-obispo': typeof LocationsSanLuisObispoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/blog'
    | '/contact'
    | '/blog/$slug'
    | '/locations/atascadero'
    | '/locations/paso-robles'
    | '/locations/san-luis-obispo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/blog'
    | '/contact'
    | '/blog/$slug'
    | '/locations/atascadero'
    | '/locations/paso-robles'
    | '/locations/san-luis-obispo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/blog'
    | '/contact'
    | '/blog/$slug'
    | '/locations/atascadero'
    | '/locations/paso-robles'
    | '/locations/san-luis-obispo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiSolutionsRoute: typeof AiSolutionsRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  LocationsAtascaderoRoute: typeof LocationsAtascaderoRoute
  LocationsPasoRoblesRoute: typeof LocationsPasoRoblesRoute
  LocationsSanLuisObispoRoute: typeof LocationsSanLuisObispoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-solutions': {
      id: '/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/ai-solutions'
      preLoaderRoute: typeof AiSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/san-luis-obispo': {
      id: '/locations/san-luis-obispo'
      path: '/locations/san-luis-obispo'
      fullPath: '/locations/san-luis-obispo'
      preLoaderRoute: typeof LocationsSanLuisObispoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/paso-robles': {
      id: '/locations/paso-robles'
      path: '/locations/paso-robles'
      fullPath: '/locations/paso-robles'
      preLoaderRoute: typeof LocationsPasoRoblesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/atascadero': {
      id: '/locations/atascadero'
      path: '/locations/atascadero'
      fullPath: '/locations/atascadero'
      preLoaderRoute: typeof LocationsAtascaderoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiSolutionsRoute: AiSolutionsRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  LocationsAtascaderoRoute: LocationsAtascaderoRoute,
  LocationsPasoRoblesRoute: LocationsPasoRoblesRoute,
  LocationsSanLuisObispoRoute: LocationsSanLuisObispoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
