/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as HomeAltRouteImport } from './routes/home-alt'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsSanLuisObispoRouteImport } from './routes/locations.san-luis-obispo'
import { Route as LocationsPasoRoblesRouteImport } from './routes/locations.paso-robles'
import { Route as LocationsAtascaderoRouteImport } from './routes/locations.atascadero'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAltRoute = HomeAltRouteImport.update({
  id: '/home-alt',
  path: '/home-alt',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSanLuisObispoRoute = LocationsSanLuisObispoRouteImport.update({
  id: '/locations/san-luis-obispo',
  path: '/locations/san-luis-obispo',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsPasoRoblesRoute = LocationsPasoRoblesRouteImport.update({
  id: '/locations/paso-robles',
  path: '/locations/paso-robles',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsAtascaderoRoute = LocationsAtascaderoRouteImport.update({
  id: '/locations/atascadero',
  path: '/locations/atascadero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-alt': typeof HomeAltRoute
  '/services': typeof ServicesRoute
  '/locations/atascadero': typeof LocationsAtascaderoRoute
  '/locations/paso-robles': typeof LocationsPasoRoblesRoute
  '/locations/san-luis-obispo': typeof LocationsSanLuisObispoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-alt': typeof HomeAltRoute
  '/services': typeof ServicesRoute
  '/locations/atascadero': typeof LocationsAtascaderoRoute
  '/locations/paso-robles': typeof LocationsPasoRoblesRoute
  '/locations/san-luis-obispo': typeof LocationsSanLuisObispoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home-alt': typeof HomeAltRoute
  '/services': typeof ServicesRoute
  '/locations/atascadero': typeof LocationsAtascaderoRoute
  '/locations/paso-robles': typeof LocationsPasoRoblesRoute
  '/locations/san-luis-obispo': typeof LocationsSanLuisObispoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/home-alt'
    | '/services'
    | '/locations/atascadero'
    | '/locations/paso-robles'
    | '/locations/san-luis-obispo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/home-alt'
    | '/services'
    | '/locations/atascadero'
    | '/locations/paso-robles'
    | '/locations/san-luis-obispo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/home-alt'
    | '/services'
    | '/locations/atascadero'
    | '/locations/paso-robles'
    | '/locations/san-luis-obispo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HomeAltRoute: typeof HomeAltRoute
  ServicesRoute: typeof ServicesRoute
  LocationsAtascaderoRoute: typeof LocationsAtascaderoRoute
  LocationsPasoRoblesRoute: typeof LocationsPasoRoblesRoute
  LocationsSanLuisObispoRoute: typeof LocationsSanLuisObispoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-alt': {
      id: '/home-alt'
      path: '/home-alt'
      fullPath: '/home-alt'
      preLoaderRoute: typeof HomeAltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/san-luis-obispo': {
      id: '/locations/san-luis-obispo'
      path: '/locations/san-luis-obispo'
      fullPath: '/locations/san-luis-obispo'
      preLoaderRoute: typeof LocationsSanLuisObispoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/paso-robles': {
      id: '/locations/paso-robles'
      path: '/locations/paso-robles'
      fullPath: '/locations/paso-robles'
      preLoaderRoute: typeof LocationsPasoRoblesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/atascadero': {
      id: '/locations/atascadero'
      path: '/locations/atascadero'
      fullPath: '/locations/atascadero'
      preLoaderRoute: typeof LocationsAtascaderoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HomeAltRoute: HomeAltRoute,
  ServicesRoute: ServicesRoute,
  LocationsAtascaderoRoute: LocationsAtascaderoRoute,
  LocationsPasoRoblesRoute: LocationsPasoRoblesRoute,
  LocationsSanLuisObispoRoute: LocationsSanLuisObispoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
